apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-api-sa
  namespace: todo-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::770651355076:role/todo-api-dev-cluster-todo-api-sa-role